config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'admin#index'

    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_parameters, :on => :member
    end
    resources :routes
    resources :users
    resources :tickets, :except => [:new, :create]
  end

  resources :users do
    resources :tickets, :except => [:edit, :update]
  end

  resource  :search
  resources :cabinet, only: :index

  root 'searches#show'

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  def delete_station(station)
    self.stations.delete(station)
    send :set_name
    self.save
  end

  private

  def set_name
    if self.stations.empty?
      self.name = "Без станций"
    elsif self.stations.nil?
      self.name = "#{self.stations.first.title} - #{self.stations.last.title}"
    end
  end

  def stations_count
    if stations.size < 2
      errors.add(:base, 'Маршрут должен содержать минимум 2 станции')
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to [:admin, @route], notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path, notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_url, notice: t('.notice')
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, station_ids: [])
  end

end

app/views/admin/routes/_form.html.erb
<%= form_for([:admin, route], html: {style: "display: #{hidden ? 'none' : 'block'};"}) do |f| %>
  <%= render 'common/errors', resource: route %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field" style="<%= small ? 'display: none' : '' %>">
    <%= f.label :station_ids %>:<br>
    <%=
      f.collection_select :station_ids, RailwayStation.all, :id, :title, {}, {:multiple => true}
    %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: route.new_record? ? t('common.action.create') : t('common.action.edit')) %>
    <% if small %>
        <%= f.button "Отменить", class: "btn_route_cancel", data: { route_id: route.id }, type: 'button' %>
    <% end %>
  </div>
<% end %>

app/views/admin/routes/_route.html.erb
<tr>
  <td>
    <div class="route_title" id="route_title_<%= route.id %>" data-route-id="<%= route.id %>" onmouseover="this.style.border = '1px dotted blue'" onmouseout="this.style.border=''">
        <%= route.name %>
    </div>
    <%= render 'form', route: route, hidden: true, small: true %>
  </td>
  <td><%= link_to t('common.action.show'), [:admin, route] %></td>
  <td><%= link_to t('common.action.edit'), edit_admin_route_path(route), class: 'edit_route', data: {route_id: route.id} %></td>
  <td><%= link_to t('common.action.delete'), [:admin, route], method: :delete, data: { confirm: t('common.action.confirm') } %></td>
</tr>

app/views/admin/routes/add_stations.html.erb
<p id="error"><%= error %></p>

<h1><%= t('.title') + ' ' + @route.name %></h1>

<%= form_for [:admin, @route], :url => url_for(:action => 'update_stations') do |f| %>
    <div class="field">
      <%=
       f.collection_select :stations, @railway_stations, :id, :title, {}, {:multiple => true}
      %>
    </div>
    <div class="actions">
      <%= f.submit t('.submit') %>
    </div>
<% end %>

<%= link_to t('common.action.back'), admin_route_path(@route) %>

app/views/admin/routes/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route, hidden: false, small: false %>

<%= link_to t('common.action.show'), [:admin, @route] %> |
<%= link_to t('common.action.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<% content_for :title do %><%= t('.title') %>
<% end %>

<h2><%= t('.title') %></h2>

<div class="row">
  <div class="col-md-12">.
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('activerecord.attributes.route.name') %></th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <%= render @routes %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to t('common.action.create'), new_admin_route_path, class: "btn btn-primary btn-sm", style: 'color:white' %>
    <%= link_to t('common.action.back'), admin_root_path, class: "btn btn-primary btn-sm", style: 'color:white' %>
  </div>
</div>

app/views/admin/routes/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form', route: @route, hidden: false, small: false %>

<%= link_to t('common.action.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.route.name') %>:</strong>
  <%= @route.name %>
</p>

<p>
  <strong><%= t('.trains_title') %></strong>
</p>

<p>
  <% if @route.trains.empty? %>
      <%= t('common.empty_list') %>
  <% else %>
    <ul>
      <% @route.trains.each do |train| %>
          <li><%= train.number %></li>
      <% end %>
    </ul>
<% end %>
</p>

<p>
  <strong><%= t('.stations_title') %></strong>
</p>

<p>
  <% if @route.stations.empty? %>
      <%= t('common.empty_list') %>
  <% else %>
    <table>
      <thead>
        <th><%= t('activerecord.attributes.railway_stations_route.railway_station') %></th>
        <th><%= t('activerecord.attributes.railway_stations_route.position') %></th>
        <th><%= t('activerecord.attributes.railway_stations_route.arrival_time') %></th>
        <th><%= t('activerecord.attributes.railway_stations_route.departure_time') %></th>
      <th></th>
      </thead>
      <tbody>
          <% @route.stations.ordered.each do |railway_station| %>
            <tr>
                <td width="100px"><%= railway_station.title %>
                <%= form_tag(update_parameters_admin_railway_station_path(railway_station), method: :patch) do %>
                    <%= hidden_field_tag :route_id, @route.id %>
                    <td><%= number_field_tag :position, railway_station.position(@route) %></td>
                    <td><%= time_field_tag :arrival_time, railway_station.arrival_time(@route) %></td>
                    <td><%= time_field_tag :departure_time, railway_station.departure_time(@route) %></td>
                    <td><%= submit_tag t('common.action.edit') %></td>
                <% end %>
            </tr>
          <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<%= link_to t('common.action.edit'), edit_admin_route_path(@route) %> |
<%= link_to t('common.action.back'), admin_routes_path %>