config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'admin#index'

    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_parameters, :on => :member
    end
    resources :routes
    resources :users
    resources :tickets, :except => [:new, :create]
  end

  resources :users do
    resources :tickets, :except => [:edit, :update]
  end

  resource  :search
  resources :cabinet, only: :index

  root 'searches#show'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :train
  belongs_to :user
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  validates :train, :start_station, :end_station, :fio, :passport, presence: true

  after_create :send_notification
  after_destroy :send_notification_cancel

  def route_name
    "#{start_station.title} - #{end_station.title}"
  end

  private

  def send_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_notification_cancel
    TicketsMailer.cancel_ticket(self.user, self).deliver_now
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_train, :set_stations, only: [:update]

  # GET /tickets
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  def show
  end

  # GET /tickets/1/edit
  def edit
    @stations = RailwayStation.all
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to [:admin, @ticket], notice: t('.notice')
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to admin_tickets_path(@ticket), notice: t('.notice')
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_train
    @train = Train.find(ticket_params[:train_id])
  end

  def set_stations
    @start_station = RailwayStation.find(ticket_params[:start_station_id])
    @end_station = RailwayStation.find(ticket_params[:end_station_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:user_id, :train_id, :start_station_id, :end_station_id, :fio, :passport)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :set_train, :set_stations, only: [:new, :create]
  before_action :authenticate_user!

  # GET /tickets
  def index
    @tickets = current_user.tickets.all
  end

  # GET /tickets/1
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = @user

    if @ticket.save
      redirect_to user_tickets_path(@user, @ticket), notice: 'Билет успешно куплен.'
    else
      render :new
    end
  end

  # PATCH/PUT /tickets/1
  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket, notice: 'Билет успешно обновлен.'
    else
      render :edit
    end
  end

  # DELETE /tickets/1
  def destroy
    @ticket.destroy
    redirect_to user_tickets_path(@user), notice: 'Билет успешно удален.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    #@user = params.try(:user_id) ? User.find(params.try(:user_id)) : User.first
    @user = User.find(params[:user_id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_train
    @train = Train.find(ticket_params[:train_id])
  end

  def set_stations
    @start_station = RailwayStation.find(ticket_params[:start_station_id])
    @end_station = RailwayStation.find(ticket_params[:end_station_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:user_id, :train_id, :start_station_id, :end_station_id, :fio, :passport)
  end

end

app/views/admin/tickets/_form.html.erb
<%= form_for([:admin, @ticket]) do |f| %>
  <%= render 'common/errors', resource: @ticket %>

  <div class="field">
    <%= f.label :train %>
    <%= f.select :train_id, options_from_collection_for_select( Train.all, "id", "number", @ticket.train.try(:id) ) %>
  </div>

  <div class="field">
    <%= f.label :start_station %>
    <%= f.select :start_station_id, options_from_collection_for_select( @stations, "id", "title", @ticket.start_station.try(:id) ) %>
  </div>

  <div class="field">
    <%= f.label :end_station %>
    <%= f.select :end_station_id, options_from_collection_for_select( @stations, "id", "title", @ticket.end_station.try(:id) ) %>
  </div>

  <div class="field">
    <%= f.label :fio %>
    <%= f.text_field :fio %>
  </div>

  <div class="field">
    <%= f.label :passport %>
    <%= f.text_field :passport %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: @ticket.new_record? ? t('common.action.buy') : t('common.action.edit')) %>
  </div>
<% end %>

app/views/admin/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.train.number %></td>
  <td><%= ticket.start_station.title %></td>
  <td><%= ticket.end_station.title %></td>
  <td><%= ticket.fio %></td>
  <td><%= ticket.passport %></td>
  <td><%= link_to t('common.action.show'), admin_ticket_path(ticket) %></td>
  <td><%= link_to t('common.action.edit'), edit_admin_ticket_path(ticket) %></td>
  <td><%= link_to t('common.action.delete'), admin_ticket_path(ticket), method: :delete, data: { confirm: t('common.action.confirm') } %></td>
</tr>

app/views/admin/tickets/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.action.show'), [:admin, @ticket] %> |
<%= link_to t('common.action.back'), admin_tickets_path %>

app/views/admin/tickets/index.html.erb
<% content_for :title do %><%= t('.title') %><% end %>
<div class="row">
  <div class="col-md-12">
    <h2><%= t('.title') %></h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= t('activerecord.attributes.ticket.train') %></th>
        <th><%= t('activerecord.attributes.ticket.start_station') %></th>
        <th><%= t('activerecord.attributes.ticket.end_station') %></th>
        <th><%= t('activerecord.attributes.ticket.fio') %></th>
        <th><%= t('activerecord.attributes.ticket.passport') %></th>
      </tr>
      </thead>

      <tbody>
      <%= render @tickets %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to t('common.action.back'), admin_root_path %>

app/views/admin/tickets/show.html.erb
<p>
  <strong><%= t('activerecord.attributes.ticket.train') %>:</strong>
  <%= @ticket.train.number %>
</p>

<p>
  <strong><%= t('activerecord.attributes.ticket.start_station') %>:</strong>
  <%= @ticket.start_station.title %>
</p>

<p>
  <strong><%= t('activerecord.attributes.ticket.end_station') %>:</strong>
  <%= @ticket.end_station.title %>
</p>

<p>
  <strong><%= t('activerecord.attributes.ticket.fio') %>:</strong>
  <%= @ticket.fio %>
</p>

<p>
  <strong><%= t('activerecord.attributes.ticket.passport') %>:</strong>
  <%= @ticket.passport %>
</p>

<%= link_to t('common.action.back'), admin_tickets_path %>