config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'admin#index'

    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_parameters, :on => :member
    end
    resources :routes
    resources :users
    resources :tickets, :except => [:new, :create]
  end

  resources :users do
    resources :tickets, :except => [:edit, :update]
  end

  resource  :search
  resources :cabinet, only: :index

  root 'searches#show'

end

app/models/train.rb
class Train < ActiveRecord::Base
  has_many :tickets
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :wagons
  has_many :carriages

  validates :number, presence: true

  # use: train.places_count("SleepingWagon", :bottom_places)
  def places_count(wagon_type, place_type)
    self.wagons.where(type: wagon_type).sum(place_type)
  end

  def sorted_wagons
    if self.sorting_wagons
      Wagon.sorting_desc
    else
      Wagon.sorting_asc
    end
  end

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  def index
    @trains = Train.all
  end

  # GET /trains/1
  def show
    @compartments = @train.wagons.where(wagon_type: 'Compartment' )
    @reserved_seat = @train.wagons.where(wagon_type: 'ReservedSeat' )

  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to [:admin, @train], notice: 'Поезд успешно создан.'
    else
      render :new
    end
  end

  # PATCH/PUT /trains/1
  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: 'Поезд успешно обновлен.'
    else
      render :edit
    end
  end

  # DELETE /trains/1
  def destroy
    @train.destroy
    redirect_to admin_trains_url, notice: 'Поезд успешно удален.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :route_id, :sorting_wagons)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for([:admin, train], html: {style: "display: #{hidden ? 'none' : 'block'};"}) do |f| %>
  <%= render 'common/errors', resource: train %>

    <div class="field">
        <%= f.label :number %><br>
        <%= f.text_field :number %>
    </div>

    <div class="field" style="<%= small ? 'display: none' : '' %>">
        <%= f.label :route %>
        <%= f.collection_select :route_id, Route.all, :id, :name %>
    </div>

    <div class="field" style="<%= small ? 'display: none' : '' %>">
        <%= f.label :sorting_wagons %>
        <%= f.select :sorting_wagons, [['с головы поезда', false], ['с хвоста поезда', true]] %>
    </div>

    <div class="actions">
        <%= f.submit "#{train.new_record? ? 'Создать' : 'Изменить'}" %>
        <% if small %>
            <%= f.button "Отменить", class: "btn_train_cancel", data: { train_id: train.id }, type: 'button' %>
        <% end %>
    </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div class="train_title" id="train_title_<%= train.id %>" data-train-id="<%= train.id %>" onmouseover="this.style.border = '1px dotted blue'" onmouseout="this.style.border=''">
        <%= train.number %>
    </div>
    <%= render 'form', train: train, hidden: true, small: true %>
  </td>
  <td><%= link_to 'Показать', [:admin, train] %></td>
  <td><%= link_to 'Изменить', edit_admin_train_path(train), class: 'edit_train', data: {train_id: train.id} %></td>
  <td><%= link_to 'Удалить', [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Редактирование поезда</h1>

<%= render 'form', train: @train, hidden: false, small: false %>

<%= link_to 'Показать', [:admin, @train] %> |
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/index.html.erb
<% content_for :title do %><%= t('.title') %>
<% end %>

<h2><%= t('.title') %></h2>

<div class="row">
  <div class="col-md-12">.
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Номер</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <%= render @trains %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Новый поезд', new_admin_train_path, class: "btn btn-primary btn-sm", style: 'color:white' %>
    <%= link_to 'Назад', admin_root_path, class: "btn btn-primary btn-sm", style: 'color:white' %>
  </div>
</div>

app/views/admin/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', train: @train, hidden: false, small: false %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>Текущий маршрут: </strong>

  <% if @train.route %>
    <%= @train.route.name %>
  <% else %>
    Маршрут не назначен
  <% end %>
</p>

<p>
    Купейных вагонов: <%= @compartments.count %>
    <p>
        Верхних мест: <%= @compartments.sum(:top_places) %>
    </p>
    <p>
        Нижних мест: <%= @compartments.sum(:bottom_places) %>
    </p>
</p>

<p>
    Плацкартных вагонов: <%= @reserved_seat.count %>
    <p>
      Верхних мест: <%= @reserved_seat.sum(:top_places) %>
    </p>
    <p>
      Нижних мест: <%= @reserved_seat.sum(:bottom_places) %>
    </p>
</p>

<p>
  <strong>Вагоны в поезде</strong>
</p>

<p>
  <% if @train.wagons.empty? %>
      Список пуст
  <% else %>
    <ul>
      <% @train.sorted_wagons.each do |wagon| %>
          <li><%= link_to (wagon.number || 'Не задан'), admin_wagon_path(wagon) %></li>
      <% end %>
    </ul>
<% end %>
</p>

<p>
  <%= link_to 'Добавить вагон', new_admin_train_wagon_path(@train) %>
</p>


<%= link_to 'Изменить', edit_admin_train_path(@train) %> |
<%= link_to 'Назад', admin_trains_path %>