config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root 'admin#index'

    resources :trains do
      resources :wagons, shallow: true
    end
    resources :railway_stations do
      patch :update_parameters, :on => :member
    end
    resources :routes
    resources :users
    resources :tickets, :except => [:new, :create]
  end

  resources :users do
    resources :tickets, :except => [:edit, :update]
  end

  resource  :search
  resources :cabinet, only: :index

  root 'searches#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :tickets

  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to [:admin, @user], notice: 'Пользователь успешно создан.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'Пользователь успешно обновлен.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: 'Пользователь успешно удален.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:user_id, :name)
  end


end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <%= render 'common/errors', resource: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </div>

  <div class="actions">
    <%= f.submit "#{@user.new_record? ? 'Создать' : 'Изменить'}" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.email %></td>
  <td><%= user.name %></td>
  <td><%= user.admin? ? 'x' : '' %></td>
  <td></td>
  <td><%= link_to 'Показать', [:admin ,user] %></td>
  <td><%= link_to 'Изменить', edit_admin_user_path(user) %></td>
  <td><%= link_to 'Изменить2', edit_user_registration_path(user) %></td>
  <td><%= link_to 'Удалить', [:admin ,user], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form' %>

<%= link_to 'Показать', [:admin, @user] %> |
<%= link_to 'Назад', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Список пользователей</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Имя</th>
      <th>Админ</th>
    </tr>
  </thead>

  <tbody>
    <%= render @users %>
  </tbody>
</table>

<br>

<%= link_to 'Новый пользователь', new_admin_user_path %>
<%= link_to 'Назад', admin_root_path %>

app/views/admin/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>Имя:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Администратор:</strong>
  <%= @user.admin? ? 'Да' : 'Нет' %>
</p>

<p>
  <strong>Купленные билеты</strong>
</p>

<p>
  <% if @user.tickets.empty? %>
      Список пуст
  <% else %>
    <table>
      <thead>
        <th>№ билета</th>
        <th>Поезд</th>
        <th>Станция отправления</th>
        <th>Станция прибытия</th>
      </thead>
      <tbody>
        <% @user.tickets.each do |ticket| %>
          <tr>
            <td>
              <%= ticket.id %>
            </td>
            <td>
              <%= ticket.train.number %>
            </td>
            <td>
              <%= ticket.start_station.title %>
            </td>
            <td>
              <%= ticket.end_station.title %>
            </td>
          </tr>
        <% end %>
    </tbody>
    </table>
<% end %>
</p>

<%= link_to 'Изменить', edit_admin_user_path(@user) %> |
<%= link_to 'Назад', admin_users_path %>